name = "AuxQuad"
uuid = "b59dd6d0-509b-4777-bfd1-cd8479d7b9e5"
authors = ["lxvm <lorenzo@vanmunoz.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
